# Generated by Django 2.1.3 on 2018-12-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
